# Generated by Django 5.1.4 on 2025-01-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServiço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('serviço', 'Serviço')], default='produto', max_length=50)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servicos', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto / Serviço',
                'verbose_name_plural': 'Produtos / Serviços',
            },
        ),
    ]
