# Generated by Django 5.1.4 on 2025-01-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_contrato_delete_produtoserviço'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='produto',
        ),
    ]
